name: packaging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: omnisci-ds-installer
        channels: conda-forge

    - name: install dependencies
      shell: bash -l {0}
      run: conda install constructor

    - name: run constructor
      shell: bash -l {0}
      run: constructor constructor/

    - uses: actions/upload-artifact@v2
      with:
        name: OmniSci-Data-Science-Installer
        path: omnisci-*-MacOSX-x86_64.pkg